In [3]:
x = 'abcd'
for i in x:
    print(i.upper())

A
B
C
D


In [ ]:
ABCD

In [ ]:
A
B
C
D

Write a Python program which iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [6]:
for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizzbuzz
46
47
fizz
49
buzz


In [1]:
for number in range(1,51):
    if number % 3 == 0 and number % 5 == 0:
        print("FizzBuzz")
        continue
    elif number % 3 == 0:
        print("Fizz")
        continue
    elif number % 5 == 0:
        print("Buzz")
        continue
    print(number)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


Write a program to create function calculation() such that it can accept two variables and calculate addition and subtraction. Also, it must return both addition and subtraction in a single return call.

In [11]:
def calculation(a,b):
    e=a+b
    d=a-b
    print("addition is : ",e)
    print("subtraction is : ",d)
calculation(3,5)

addition is :  8
subtraction is :  -2


In [8]:
def calculation(a, b):
    addition = a + b
    subtraction = a - b
    return addition, subtraction

result = calculation(10, 5)
print("Addition:", result[0])
print("Subtraction:", result[1])

Addition: 15
Subtraction: 5


In [2]:
def calculation(a,b):
    print(a+b)
    print(a-b)

In [3]:
calculation(4,5)

9
-1


In [4]:
calculation(9,1)

10
8


In [33]:
def calculation(a,b):
    print(a+b)
    print(a-b)

In [34]:
calculation(10,20)

30
-10


In [35]:
def addsub(x,y):
    add = x+y
    sub = x-y
    return add,sub


In [36]:
addsub(10,20)

(30, -10)

In [37]:
def calculation(a, b):
    addition = a + b
    subtraction = a - b
    # return multiple values separated by comma
    return addition, subtraction


In [38]:
calculation(40, 10)

(50, 30)

Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string already ends with 'ing' then add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged.

In [5]:
def function(string):
  length = len(string)

  if length > 2:
    if string[-3:] == 'ing':
      string += 'ly'
    else:
      string += 'ing'

  return string

In [8]:
print(function('wo'))

wo


In [12]:
a=str(input("Enter the string: "))
for i in a:
    if len(a)<3:
        break
    elif a[-3:]=="ing":
        a=a+"ly"
        print("a")
    else:
        a=a+"ing"
        print("a")

Enter the string: abc
a
a
a


In [39]:
def add(str):
    length = len(str)

    if length>=3:
        if str[-3:] == 'ing':
          str = str+ 'ly'
        else:
          str = str+ 'ing'


    return str


In [40]:
print(add('playing'))

playingly


In [42]:
str=input()
l=len(str)
if l<3:
    print(str)
else:
    if str[-3:]=='ing':
        str=str+"ly"
    else:
        str=str+"ing"
    print(str)


abc
abcing


In [43]:
def add_string(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1

In [44]:
add_string('ab')

'ab'

In [45]:
add_string('abc')

'abcing'

In [46]:
add_string('string')

'stringly'

Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [9]:
import numpy as np
x = np.zeros(10,dtype=int)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [48]:
import numpy as np
a = np.array([0,0,0,0,0,0,0,0,0,0])
a
a[6] = 11
a

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0])

In [49]:
a=np.zeros(10,dtype=int)
a[0] = 11
print(a)

[11  0  0  0  0  0  0  0  0  0]


In [50]:
import numpy as np
x = np.zeros(10,dtype=int)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0 0 0 0 0 0 0 0 0 0]
Update sixth value to 11
[ 0  0  0  0  0  0 11  0  0  0]


Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [ ]:
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]

In [13]:
a=np.zeros((8,8),dtype=int)
a[1::2, ::2]= 1
a[:: 2, 1::2]=2
a

array([[0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 2, 0, 2, 0, 2, 0, 2],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [53]:
x = np.ones((8,8),dtype=int)
x[::2,::2] = 0
x[::2,0::2] = 0
print(x)

[[0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]]


In [54]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
#Write a NumPy program to create a new array of 3*5, filled with 2.

In [56]:
a = np.zeros((3,5), dtype= int)
a[:] = 2
a

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [57]:
a = np.zeros((3,5),dtype=int)
a[::1, ::1]= 2
a[:: 1, 1::1]=2
a

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])